import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
import { LegalPage, Section, NoCashValueNotice } from "@/components/legal/LegalPage";

export const metadata: Metadata = pageMetadata(
  "Terms of Service",
  "The rules for using WinIt — a play-money casino and sports-betting simulation with no cash value.",
);

const UPDATED = "September 28, 2026";

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated={UPDATED}
      intro={
        <>
          These Terms govern your use of WinIt. By creating an account or using the site, you agree to them. If you
          don&apos;t agree, don&apos;t use WinIt.
        </>
      }
    >
      <NoCashValueNotice />

      <Section title="1. What WinIt is">
        <p>
          WinIt is a simulated casino and sportsbook. Every game — dice, roulette, blackjack, the sports section, all
          of it — runs on play money only. It exists for entertainment, to demonstrate game logic and odds maths, and
          as a portfolio project.
        </p>
        <p>
          WinIt is <strong className="text-slate-200">not</strong> a real-money gambling service, is not licensed as
          one, and does not offer, and will never offer, any way to deposit real money, purchase credits with real
          money, or withdraw, cash out, or otherwise convert any in-app balance into real money, cryptocurrency,
          goods, or anything else of value.
        </p>
      </Section>

      <Section title="2. Who can use WinIt">
        <p>
          You must be at least 18 years old, or the age of majority where you live if that&apos;s higher, to create
          an account. By signing up you confirm that you meet this requirement.
        </p>
        <p>
          You&apos;re responsible for using WinIt only where doing so is lawful. Because WinIt involves no real
          money, wagering, or prize of value, it is not gambling under most laws — but you&apos;re responsible for
          checking the rules that apply to you.
        </p>
        <p>One account per person. Accounts created to abuse referrals, promo codes, or the daily bonus may be closed.</p>
      </Section>

      <Section title="3. No cash value, ever">
        <p>
          Chips, credits, balances, XP, levels, rebirths, and every number this app shows you are internal game
          state. They are not currency, not a security, not a gift card, and not redeemable for anything. This will
          never change, and no feature of WinIt will ever let you buy a balance with real money or turn a balance
          into real money.
        </p>
        <p>
          If WinIt ever sells anything for real money — a subscription, a cosmetic item — that purchase is for the
          item or feature itself, never for chips, credits, or an improved chance of winning them.
        </p>
      </Section>

      <Section title="4. The sports section">
        <p>
          WinIt&apos;s sports section uses real sporting events and real bookmaker odds, sourced from a third-party
          data provider, purely to make the numbers realistic. Bets there are settled against real final scores, but
          every stake and every payout is play money under the same rule as the rest of the app — no cash value, no
          exceptions.
        </p>
      </Section>

      <Section title="5. Your account and conduct">
        <p>Keep your password to yourself. You&apos;re responsible for activity on your account.</p>
        <p>Don&apos;t:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Use bots, scripts, or exploits to play games or farm rewards</li>
          <li>Create multiple accounts to abuse referrals, promo codes, or bonuses</li>
          <li>Attempt to buy, sell, or trade any WinIt account or balance</li>
          <li>Harass other players or post abusive content in chat</li>
          <li>Attempt to disrupt, reverse-engineer for malicious purposes, or attack the service</li>
        </ul>
        <p>
          WinIt records infractions as strikes. Enough strikes suspends an account; a further one can ban it
          outright. We may suspend or terminate any account at our discretion, especially for the conduct above.
        </p>
      </Section>

      <Section title="6. Intellectual property">
        <p>
          The WinIt name, design, and code are owned by its operator or licensed to it. You may not copy, resell, or
          represent WinIt as your own work.
        </p>
      </Section>

      <Section title="7. No warranty">
        <p>
          WinIt is provided &ldquo;as is,&rdquo; without warranties of any kind. We don&apos;t guarantee the service
          will be uninterrupted, error-free, or available at all times. Game outcomes are generated by the
          algorithms described in-app; published return-to-player figures describe long-run behaviour, not any
          individual result.
        </p>
      </Section>

      <Section title="8. Limitation of liability">
        <p>
          Because no real money, currency, or prize of value ever moves through WinIt, our liability to you is
          limited to the fullest extent the law allows. We are not liable for indirect, incidental, or consequential
          damages arising from your use of the service.
        </p>
      </Section>

      <Section title="9. Changes">
        <p>
          We may update these Terms as WinIt changes. We&apos;ll update the date at the top of this page when we do.
          Continuing to use WinIt after a change means you accept the update.
        </p>
      </Section>

      <Section title="10. Termination">
        <p>
          You can stop using WinIt at any time. We can suspend or close an account for violating these Terms, for
          extended inactivity, or if we discontinue the service.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms? Reach out at{" "}
          <a href="mailto:support@winit.app" className="text-volt hover:underline">
            support@winit.app
          </a>
          .
        </p>
        <p className="text-slate-500">
          See also our{" "}
          <Link href="/legal/privacy" className="text-volt hover:underline">
            Privacy Policy
          </Link>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
